version: '3.1'

services:
  db:
    image: mysql:8.0
    command:  --max_connections=1000 --default-authentication-plugin=mysql_native_password --max_allowed_packet=128M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: trade_order
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQLD_JOIN_BUFFER_SIZE: 128
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro 

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
    db_data: {}