basePath: /api/v1
host: http://localhost:8080
info:
  contact:
    email: support@swagger.io
    name: errorfatal89@gmail.com
    url: http://www.swagger.io/support
  description: http server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: http server
  version: "1.0"
paths: {}
swagger: "2.0"
